name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  HUSKY: 0

jobs:
  test:
    name: "Check ${{ matrix.test }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ["prettier", "test", "cypress"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install dependencies
        run: pnpm i
      - name: Run test
        run: pnpm run ${{ matrix.test }}
